"""
Django settings for cloudlab project.

Generated by 'django-admin startproject' using Django 5.2.9.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path
import environ

env = environ.Env()
environ.Env.read_env(os.path.join(Path(__file__).resolve().parent.parent, '.env'))

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Loaded from environment via django-environ; fallback for local dev
SECRET_KEY = env('SECRET_KEY', default='dev-insecure-change-me-please')

# SECURITY WARNING: don't run with debug turned on in production!
# Default True for local dev; set DEBUG=False in production env
DEBUG = env.bool('DEBUG', default=True)

def _normalize_host(value: str) -> str:
    host = value.strip()
    if host.startswith('http://'):
        host = host[len('http://'):]
    elif host.startswith('https://'):
        host = host[len('https://'):]
    return host.rstrip('/')


# Comma-separated hosts in env, e.g. "127.0.0.1,localhost,.onrender.com,.railway.app,.vercel.app"
_default_hosts = ['127.0.0.1', 'localhost', '.onrender.com', '.railway.app', '.vercel.app']
_env_hosts = env.list('ALLOWED_HOSTS', default=_default_hosts)
_render_host = env('RENDER_EXTERNAL_HOSTNAME', default='')
if _render_host:
    _env_hosts.append(_render_host)
ALLOWED_HOSTS = list(dict.fromkeys([_normalize_host(h) for h in _env_hosts if h and _normalize_host(h)]))


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'portfolioapi',
    'corsheaders',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# CORS settings: allow frontend origins from Vercel, Railway, Render, and local dev
CORS_ALLOWED_ORIGINS = env.list('CORS_ALLOWED_ORIGINS', default=[
    "https://emiliokamau.vercel.app",
    "http://127.0.0.1:3000",
    "http://localhost:3000",
    "http://127.0.0.1:5500",
    "http://localhost:5500",
])
# For testing only, you can use the permissive option below
# CORS_ALLOW_ALL_ORIGINS = True

# CSRF trusted origins when using cookie-based POSTs from frontend
CSRF_TRUSTED_ORIGINS = [
    "https://emiliokamau.vercel.app",
    "https://portfolio-emiliokamau.up.railway.app",
    "https://*.onrender.com",
]

# Ensure Django correctly detects HTTPS behind Railway's proxy
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# Secure cookies when served over HTTPS (recommended for production)
CSRF_COOKIE_SECURE = True
SESSION_COOKIE_SECURE = True

# HTTPS hardening for production; keep local development flexible.
SECURE_SSL_REDIRECT = env.bool('SECURE_SSL_REDIRECT', default=not DEBUG)
SECURE_HSTS_SECONDS = env.int('SECURE_HSTS_SECONDS', default=31536000 if not DEBUG else 0)
SECURE_HSTS_INCLUDE_SUBDOMAINS = env.bool('SECURE_HSTS_INCLUDE_SUBDOMAINS', default=not DEBUG)
SECURE_HSTS_PRELOAD = env.bool('SECURE_HSTS_PRELOAD', default=False)

# Ensure Django builds absolute URLs correctly behind proxy
USE_X_FORWARDED_HOST = True

# Cookie same-site policies to allow login redirects
CSRF_COOKIE_SAMESITE = 'Lax'
SESSION_COOKIE_SAMESITE = 'Lax'

# Optional: explicit login redirect after successful auth
LOGIN_REDIRECT_URL = '/airlock/'

ROOT_URLCONF = 'cloudlab.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            os.path.join(BASE_DIR, 'templates'),
            str(BASE_DIR.parent),
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]
WSGI_APPLICATION = 'cloudlab.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# Database: use DATABASE_URL if provided (Render/Railway Postgres), else fallback to sqlite
try:
    DATABASES = {
        'default': env.db('DATABASE_URL')
    }
except Exception:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static')
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Media files
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# Email settings: SendGrid
# Using SendGrid to avoid conflicts with other applications using same SMTP
DEFAULT_FROM_EMAIL = env('SENDGRID_FROM_EMAIL', default='noreply@portfolio.local')
EMAIL_BACKEND = 'sendgrid_backend.SendgridBackend'
SENDGRID_API_KEY = env('SENDGRID_API_KEY', default='')

# Optional: SMTP fallback (if SendGrid not available)
# EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# EMAIL_HOST = env('EMAIL_HOST', default='smtp.gmail.com')
# EMAIL_PORT = env.int('EMAIL_PORT', default=587)
# EMAIL_USE_TLS = env.bool('EMAIL_USE_TLS', default=True)
# EMAIL_HOST_USER = env('EMAIL_HOST_USER', default='')
# EMAIL_HOST_PASSWORD = env('EMAIL_HOST_PASSWORD', default='')

# Twilio settings for WhatsApp/SMS integration
# Using separate Twilio account to avoid conflicts with other applications
TWILIO_ACCOUNT_SID = env('TWILIO_ACCOUNT_SID', default='')
TWILIO_AUTH_TOKEN = env('TWILIO_AUTH_TOKEN', default='')
TWILIO_WHATSAPP_FROM = env('TWILIO_WHATSAPP_FROM', default='')  # e.g., 'whatsapp:+1234567890'
TWILIO_PHONE_FROM = env('TWILIO_PHONE_FROM', default='')  # e.g., '+1234567890' for SMS
TWILIO_OWNER_WHATSAPP_TO = env('TWILIO_OWNER_WHATSAPP_TO', default='')  # your WhatsApp, e.g. 'whatsapp:+2547...'
TWILIO_WHATSAPP_CONTENT_SID = env('TWILIO_WHATSAPP_CONTENT_SID', default='')  # Twilio template content sid (optional)

# Integrations
SLACK_WEBHOOK_URL = env('SLACK_WEBHOOK_URL', default='')

# Frontend routing
FRONTEND_BASE_URL = env('FRONTEND_BASE_URL', default='https://emiliokamau.vercel.app')
FRONTEND_LANDING_PATH = env('FRONTEND_LANDING_PATH', default='/landing.html')
if FRONTEND_LANDING_PATH.startswith('/'):
    FRONTEND_LANDING_URL = f"{FRONTEND_BASE_URL.rstrip('/')}{FRONTEND_LANDING_PATH}"
else:
    FRONTEND_LANDING_URL = f"{FRONTEND_BASE_URL.rstrip('/')}/{FRONTEND_LANDING_PATH}"
