# Generated by Django 5.2.9 on 2025-12-10 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioapi', '0002_skill'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='icon',
            field=models.CharField(default='default.svg', max_length=100),
        ),
    ]
