# Generated by Django 5.2.9 on 2026-03-20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioapi', '0003_skill_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='image_three',
            field=models.ImageField(blank=True, null=True, upload_to='projects/gallery/'),
        ),
        migrations.AddField(
            model_name='project',
            name='image_two',
            field=models.ImageField(blank=True, null=True, upload_to='projects/gallery/'),
        ),
        migrations.AddField(
            model_name='resume',
            name='doc_type',
            field=models.CharField(choices=[('cv', 'CV'), ('resume', 'Resume'), ('cover_letter', 'Cover Letter')], default='resume', max_length=20),
        ),
        migrations.AddField(
            model_name='resume',
            name='title',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='resume',
            name='file',
            field=models.FileField(upload_to='credentials/'),
        ),
        migrations.CreateModel(
            name='CredentialDownloadRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('document_type', models.CharField(choices=[('cv', 'CV'), ('resume', 'Resume'), ('cover_letter', 'Cover Letter')], max_length=20)),
                ('consent_given', models.BooleanField(default=False)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('status_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
